// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8h5YdDxpOVo5vbfXf1iYqdKdDbBs5UO0',
    appId: '1:973167727452:web:9d3557a8ac707d7be16799',
    messagingSenderId: '973167727452',
    projectId: 'ourglow',
    authDomain: 'ourglow.firebaseapp.com',
    storageBucket: 'ourglow.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDAmdGVbeiZTk4qEFPoJ0WPy3e0CeASkk',
    appId: '1:973167727452:android:50bb0f2a29651334e16799',
    messagingSenderId: '973167727452',
    projectId: 'ourglow',
    storageBucket: 'ourglow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASWi-xORbnZ_EEaljg-p_yfqTLzS9bdhc',
    appId: '1:973167727452:ios:8d2b247c29f09ef6e16799',
    messagingSenderId: '973167727452',
    projectId: 'ourglow',
    storageBucket: 'ourglow.firebasestorage.app',
    iosBundleId: 'com.example.ourGlowV2',
  );
}
